default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: coding_challenges_development

test:
  <<: *default
  database: coding_challenges_test

production:
  <<: *default
  database: coding_challenges_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
